### PR TITLE
Added our new Code of Conduct for contributing.

### PR DESCRIPTION
**Pull request by emiln**
After [a fruitful discussion with Contributor Covenant](https://github.com/CoralineAda/contributor_covenant/issues/86) it was unanimously agreed to adopt that as the Code of Conduct for contributing to this project. This pull request exists merely to sort out the details of its inclusion.

### CODE REVIEW

**Comment by Mikkeren** [comment]
The Board of Directors has had an emergency meeting to hurry up the approval of this, to prove that we are very serious about openness and inclusivity, and will not tolerate harassment of any kind. I will approve this on behalf of the entire Board of EnterpriseQualityCoding.

**Comment by awonnacott** [comment]
Shouldn't the branch have been deleted?

**Comment by emiln** [comment]
Good call, @awonnacott. It is now.

**Comment by magicgoose** [comment]
Come on, what is the point in including this?
Are there any proofs that it indeed improves enterprise development in any way?

**Pull request merged**
