### PR TITLE
Internationalized the project - now English and Chinese languages are…

### PR DESCRIPTION
**Pull request by jnazander**
… available, others may be easily added.

### CODE REVIEW

**Comment by happysmash27** [comment]
Ah, why hasn't this been approved yet? It has been 12 months.

**Comment by SRGOM** [comment]
Possibly because the owners can't be sure of Chinese translation. Code review, in software as important a this, is no laughing matter

**Comment by wizzwizz4** [comment]
@happysmash27 Because Travis got a bit sick, was off work for a bit and couldn't pay his rent. #409 fixes this.

**Comment by TobiasRoland** [comment]
I have security concerns about character encoding when introducing Chinese characters, Eclipse on my Windows XP system running on the company shared development environment might not like this, as it does not natively support UTF16- could we please use the explicit unicode code, so please change it to concatinfating unicode chars like `\u2202`

**Comment by wizzwizz4** [comment]
@TobiasRoland Can't you just escape it in your IDE?

**Comment by emiln** [comment]
As a company we are deeply grateful for the many open source contributions we're receiving, but [we can no longer](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472) in good faith support merge requests into the problematically named `master` branch, which has been removed.

Instead we hope that you will reopen your merge request and target the new default branch, artisanally crafted by our Swedish Inclusivity Consultant, called `uinverse`. You can read more about the inclusivity success story [in the issue](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472).

**Pull request closed without merging**
