### PR TITLE
Look for new homes for Travis

### PR DESCRIPTION
**Pull request by commonquail**
This is better. :))))

### CODE REVIEW

**Comment by wizzwizz4** [comment]
Fixes #398 and #399, I think. Should be merged.

**Comment by wizzwizz4** [comment]
@emiln @Mikkeren This pull request is essential for the project to continue. Also, if neither of you are very active, it's probably a good idea to promote somebody else to the board of directors.

**Comment by Mikkeren** [comment]
I'm afraid this is not extensive enough to live up to our new corporate requirements.

IT Security demands that we test on every imaginable version of the Java runtime and I can see this says to "allow failures", which is absolutely unacceptable. We do not tolerate failure here at EnterpriseQualityCoding, so this needs to be IMMEDIATELY rectified before this whole matter can be dealt with.

Only when this has been sorted, can we start discussions on the full scope of available versions that needs to be tested to ensure the stability our customers have come to expect from us.

**Comment by lukaseppler** [comment]
@ Mikkeren @ wizzwizz4 let's have a conf call at the earliest possible. This needs to be addressed urgently.
--
Sent from Mail for Windows 10

**Comment by wizzwizz4** [comment]
@Mikkeren That's allowing failures in the Matrix. Every program comes with failures – it's a law of physics; no business produces failure-free programs because that's like travelling faster than the speed of light –, so we use them all up before giving the code the "red pill" (so to speak).

The Matrix is a simulated world, in which the program fails to use up its failures. Like if you flip a coin 10000000000000000000000000000000000000000000000000000 times on heads, you'll eventually use up all of the heads and only get tails, because there are no heads left.

Really, this only mentions "failure" to ensure that such a failure will never happen outside the Matrix.

**Comment by emiln** [comment]
As a company we are deeply grateful for the many open source contributions we're receiving, but [we can no longer](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472) in good faith support merge requests into the problematically named `master` branch, which has been removed.

Instead we hope that you will reopen your merge request and target the new default branch, artisanally crafted by our Swedish Inclusivity Consultant, called `uinverse`. You can read more about the inclusivity success story [in the issue](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472).

**Pull request closed without merging**
