### PR TITLE
Serious Documentation

### PR DESCRIPTION
**Pull request by ecurtin**
The Documentation Standards Committee conducted its annual year-end audit and found this project to be severely lacking. See the minutes of the annual off-site for more detail: [https://confluence.seriouscompany.com/display/~documenation_commitee/Annual+Meeting+Minutes+2015](http://i0.kym-cdn.com/photos/images/newsfeed/000/154/912/berneydidnotread.gif?1318992465)

As referenced in issue #240, documentation is an essential tool for assuring the continued maintenance of high-grade enterprise software. 

This branch increases the number of comment lines 11800% from 3 in the current master branch to 357 as counted by `cloc $(git ls-files)` This is an essential addition to ensure future maintainability.

### CODE REVIEW

**Comment by octalmage** [comment]
There's a bunch of style issues, for example: 

https://github.com/ecurtin/FizzBuzzEnterpriseEdition/blob/seriousDocumentation/src/main/java/com/seriouscompany/business/java/fizzbuzz/packagenamingpackage/impl/strategies/SingleStepPayload.java#L18

**Comment by mklopets** [comment]
Any updates?

**Comment by ecurtin** [comment]
The Documentation Standards Committee has taken note of these concerns and has plans to address them.

**Comment by ecurtin** [comment]
@octalmage @mklopets The Documentation Standards Committee appreciates your participation and is pleased to announce that it has completed a review of the 2015 Documentation Standard Concerns! Please see the new changes, including documentation for tests and for all classes, such as [this](https://github.com/ecurtin/FizzBuzzEnterpriseEdition/blob/seriousDocumentation/src/test/java/FizzBuzzTest.java#L18) and [this](https://github.com/ecurtin/FizzBuzzEnterpriseEdition/blob/seriousDocumentation/src/main/java/com/seriouscompany/business/java/fizzbuzz/packagenamingpackage/impl/strategies/EnterpriseGradeFizzBuzzSolutionStrategy.java#L12)

Remember, thorough and clear documentation is the only way to ensure maintainability for high quality Enterprise software.

**Comment by mklopets** [comment]
Thank you @ecurtin, we are pleased to see the important problems pointed out by the Documentation Standards Committee being resolved.

Me and my organisation's IT team have begun the necessary preparations to ensure that the upgrade goes smoothly on our part. As the changes you have introduced here are not *that* big, we hope to have the update pushed to our clients at the end of Q4 2019.

Our recent 2014 Internal Security Audit found a gaping security hole in the 2013 build we used back then, however. I was informed by our Chief Information Officer that the automatic LF normalisation could be used as a backdoor to our databases. **As proud contributors to Serious Company's Open Source Software, we _must_ value security™ over LF normalisation**.

Please see [dangerous line in codebase](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/blob/master/.gitattributes#L2)

**Comment by ecurtin** [comment]
The Documentation Standards Committee has completed its bi-monthly review of pending documentation, and has found that the changes submitted for the project "FizzBuzzEnterpriseEdition" are not currently up to the high standards upheld by the Documentation Standards Committee.

The Committee discovered that the new documentation was developed using a mix of the "Tabs" development paradigm and the "Spaces" development paradigm. After a thorough investigation and several reports to C-Suite management, the intern responsible was disciplined.

The Documentation Standards Committee has recommended a recent hire in the organization complete the necessary changes to bring the documentation up to standards. We appreciate the dedicated developers like @richardatsoundcloud who brought this to the attention of the Documentation Standards Committee, and we further appreciate the continued patience of the SeriousCompany developers while this matter is rectified.

Remember, thorough and clear documentation is the only way to ensure maintainability for high quality Enterprise software.

**Comment by markopavlovic** [comment]
+1

**Comment by mklopets** [comment]
@richardatsoundcloud can we get a move on this? I need to present our engineering department's Q4 accomplishments soon and this would make us look better

**Comment by mklopets** [comment]
Hi, any updates?

**Comment by Mikkeren** [comment]
After much back and forth between the The Documentation Standards Committee and our developers and several rewrites of all the documentation contained in this Request for Change, which have eventually led back to it becoming what was already included in this patch.

It has been decided we will include this very impactful upgrade to The FizzBuzzEnterpriseEdition software suite.

We apologize for the peoples whose 2015 KPIs were impacted by this change not being included at the time, but you will surely understand that we have to consider the effect on all our clients and their systems and subsystems, we obviously do not wish for a repeat of 2014s spectacle surrounding change management, which I'm sure you all are only much too familar with.

Naturally these KPIs will have carried over unchanged into 2016, which is unfortunate but I assure you all that this is a top priority for our business as a whole and we assure you this had no impact on the decision to cut your salaries at the beginning of 2017, despite the record-breaking profits for that year.

Fortunately we changed our employee evaluation system during 2017 and you were no longer affected by these KPIs, but of course you will understand that this was, and still is, a core concern for our business and that is why you were all assigned yearly targets about getting this documentation finished up.

We hope you did not feel an impact on morale or your salaries and bonuses (of which there were none) during the 2018 and 2019 years, where we have seen explosive growth in profits due to the influx of machine learning-related Fizzing and Buzzing going on in our industry.

We are **very** happy to have this change released and hope all of our clients will be able to handle incorporating the change into their workflow ASAP. This is a major milestone for the project and a perfect way to cap off the decade of progress we have all been making.

To everyone involved, a big thank you from Management at EnterpriseQualityCoding

**Pull request merged**
