### PR TITLE
Replaces "\n" for system-dependent new line char

### PR DESCRIPTION
**Pull request by JoaoGFarias**
Although I don't trust Sun code very much, this move is safer than depending on a fixed char for new lines.

### CODE REVIEW

**Comment by twinters007** [comment]
The only change you made was to add an extra whitespace character

**Comment by JoaoGFarias** [comment]
@twinters007 I tried to trigger another build. The [error in Travis](https://travis-ci.org/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/jobs/340543304#L507) seems unrelated to my changes.

**Comment by chapmanjacobd** [comment]
I really hope this gets merged soon because I'm running into some portability issues that this commit will probably resolve

**Comment by emiln** [comment]
As a company we are deeply grateful for the many open source contributions we're receiving, but [we can no longer](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472) in good faith support merge requests into the problematically named `master` branch, which has been removed.

Instead we hope that you will reopen your merge request and target the new default branch, artisanally crafted by our Swedish Inclusivity Consultant, called `uinverse`. You can read more about the inclusivity success story [in the issue](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472).

**Pull request closed without merging**
