### PR TITLE
Remove unnecessary clarification from README

### PR DESCRIPTION
**Pull request by sp-1234**
Because it's already obvious that the project is satire

### CODE REVIEW

**Comment by magicgoose** [comment]
seems legit IMO. why still no action?

**Comment by goosehub** [comment]
Wait, this is satire? I won't be renewing my contract unless this satire issue is resolved.

**Comment by emiln** [comment]
As a company we are deeply grateful for the many open source contributions we're receiving, but [we can no longer](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472) in good faith support merge requests into the problematically named `master` branch, which has been removed.

Instead we hope that you will reopen your merge request and target the new default branch, artisanally crafted by our Swedish Inclusivity Consultant, called `uinverse`. You can read more about the inclusivity success story [in the issue](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/472).

**Comment by magicgoose** [comment]
Unfortunately I'm nearly certain that it won't happen because the user who created this PR hasn't had any activity on GitHub since year 2018 (inclusive).  
We might need to ask someone else to carefully craft a new PR with the same functionality.

**Pull request closed without merging**
