### PR TITLE
Best practices: use final wherever possible, constructor injection, this. access to fields

### PR DESCRIPTION
**Pull request by krasa**
Implementation of following best practices:

Every class should be final by default, except classes explicitly designed to be extensible. Unfortunately Spring beans cannot be final - http://stackoverflow.com/questions/2657432/make-spring-service-classes-final
Also method and constructor parameters, field and variables should be final. This is a no-brainer.
 
It is recommended to use **constructor injection** instead of **field injection** to provide better testability and safety against NPE. Every object should be fully initialized upon construction.

Using .this to access fields provide a safety against accidental use of parameter/variable, thus greatly reducing a number of possible bugs..

Supersedes: #153 #172

Resources:
http://whiley.org/2011/12/06/final-should-be-default-for-classes-in-java

### CODE REVIEW

**Comment by krasa** [comment]
Also contains some minor correctness fixes, and a context holder for integration of beans with static  utility classes - it might be wise to change them into beans in future.

**Comment by mikkelee** [comment]
+1

**Comment by emiln** [comment]
I think this is a very valuable and needed contribution to the FizzBuzzEnterpriseEdition project, but it currently seems to be failing our comprehensive test suite on Travis CI. I will be happy to merge it as soon as it is back to passing our tests.

**Comment by krasa** [comment]
thank you, interesting that this commit caused it: https://github.com/krasa/FizzBuzzEnterpriseEdition/commit/a7c7d84b7df84ab540ec58b13c59dc4acec9f8dc :)
lets try rebuild....

**Comment by emiln** [comment]
I've requested a new build on Travis CI. It should start shortly.

**Pull request merged**
